#!/usr/bin/env python3
"""
Training pipeline for Smart Seal impact classifier.

Trains a 1D CNN on labeled accelerometer data and exports a TFLite Micro C header.

Usage:
    # 1. Collect data (flash with IMPACT_DATA_COLLECTION enabled):
    #    python3 -m serial.tools.miniterm --raw /dev/ttyACM0 115200 > raw_idle.csv
    #    (shake device, drop device, etc. for each session)
    #
    # 2. Label and merge:
    #    awk 'NR>1{print $0",no_impact"}'    raw_idle.csv  > labeled.csv
    #    awk 'NR>1{print $0",light_impact"}' raw_light.csv >> labeled.csv
    #    awk 'NR>1{print $0",heavy_impact"}' raw_heavy.csv >> labeled.csv
    #    sed -i '1s/^/timestamp_ms,accel_x,accel_y,accel_z,label\n/' labeled.csv
    #
    # 3. Train:
    #    python3 firmware/train_impact_model.py \
    #        --data labeled_impacts.csv \
    #        --output firmware/smart_seal/impact_model_data.h

import argparse
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report

import tensorflow as tf
from tensorflow import keras

LABEL_MAP = {"no_impact": 0, "light_impact": 1, "heavy_impact": 2}
MIN_F1 = 0.75


def load_windows(csv_path, window_size, step_size):
    df = pd.read_csv(csv_path)
    required = {"timestamp_ms", "accel_x", "accel_y", "accel_z", "label"}
    missing = required - set(df.columns)
    if missing:
        print(f"ERROR: missing columns: {missing}", file=sys.stderr)
        sys.exit(1)

    X, y = [], []
    for start in range(0, len(df) - window_size + 1, step_size):
        window = df.iloc[start : start + window_size]
        labels = window["label"].unique()
        if len(labels) != 1:
            continue  # skip mixed-label windows
        label = labels[0]
        if label not in LABEL_MAP:
            continue
        X.append(window[["accel_x", "accel_y", "accel_z"]].values.astype(np.float32))
        y.append(LABEL_MAP[label])

    if not X:
        print("ERROR: no valid windows found — check CSV format and labels", file=sys.stderr)
        sys.exit(1)

    return np.array(X), np.array(y)


def normalize(X_train, X_val):
    flat = X_train.reshape(-1, 3)
    mean = flat.mean(axis=0)
    std  = flat.std(axis=0) + 1e-8
    return (X_train - mean) / std, (X_val - mean) / std, mean, std


def build_model(window_size, n_classes):
    model = keras.Sequential([
        keras.layers.Input(shape=(window_size, 3)),
        keras.layers.Conv1D(16, kernel_size=5, activation="relu", padding="same"),
        keras.layers.Conv1D(32, kernel_size=3, activation="relu", padding="same"),
        keras.layers.GlobalAveragePooling1D(),
        keras.layers.Dense(n_classes, activation="softmax"),
    ])
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def quantize_int8(model, X_train_norm):
    def representative_dataset():
        for i in range(min(200, len(X_train_norm))):
            yield [X_train_norm[i : i + 1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def write_header(output_path, tflite_bytes, mean, std):
    lines = [
        "// Auto-generated by train_impact_model.py — do not edit manually",
        "#pragma once",
        "",
        f"const float AXIS_MEAN[3] = {{{mean[0]:.8f}f, {mean[1]:.8f}f, {mean[2]:.8f}f}};",
        f"const float AXIS_STD[3]  = {{{std[0]:.8f}f,  {std[1]:.8f}f,  {std[2]:.8f}f}};",
        "",
        f"const int g_impact_model_data_len = {len(tflite_bytes)};",
        "const unsigned char g_impact_model_data[] = {",
    ]
    hex_vals = [f"0x{b:02x}" for b in tflite_bytes]
    for i in range(0, len(hex_vals), 12):
        lines.append("  " + ", ".join(hex_vals[i : i + 12]) + ",")
    lines.append("};")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Written: {output_path}  ({len(tflite_bytes):,} bytes)")


def main():
    parser = argparse.ArgumentParser(description="Train Smart Seal impact classifier")
    parser.add_argument("--data",   required=True,  help="labeled CSV path")
    parser.add_argument("--window", type=int, default=25, help="samples per window (default 25 = 500ms @ 50Hz)")
    parser.add_argument("--step",   type=int, default=5,  help="window step size (default 5 = 100ms)")
    parser.add_argument("--output", default="firmware/smart_seal/impact_model_data.h")
    parser.add_argument("--epochs", type=int, default=30)
    args = parser.parse_args()

    print(f"Loading windows from {args.data} (window={args.window}, step={args.step})...")
    X, y = load_windows(args.data, args.window, args.step)
    counts = np.bincount(y, minlength=3)
    for name, idx in LABEL_MAP.items():
        print(f"  {name}: {counts[idx]} windows")

    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )
    X_train_n, X_val_n, mean, std = normalize(X_train, X_val)

    print("\nTraining model...")
    model = build_model(args.window, len(LABEL_MAP))
    model.summary()
    model.fit(
        X_train_n, y_train,
        validation_data=(X_val_n, y_val),
        epochs=args.epochs,
        batch_size=32,
        verbose=1,
    )

    y_pred = np.argmax(model.predict(X_val_n, verbose=0), axis=1)
    f1_per_class = f1_score(y_val, y_pred, average=None, labels=[0, 1, 2])
    print("\nValidation results:")
    print(classification_report(y_val, y_pred, target_names=list(LABEL_MAP.keys())))

    failed = [name for name, f1 in zip(LABEL_MAP.keys(), f1_per_class) if f1 < MIN_F1]
    if failed:
        print(f"ERROR: F1 < {MIN_F1} for classes: {failed} — collect more data and retrain", file=sys.stderr)
        sys.exit(1)

    print("Quantizing to INT8...")
    tflite_bytes = quantize_int8(model, X_train_n)

    write_header(args.output, tflite_bytes, mean, std)
    print("Done. Flash the firmware to pick up the new model.")


if __name__ == "__main__":
    main()
